# Generated by Django 4.2.2 on 2023-06-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colheitas',
            fields=[
                ('id_colheita', models.AutoField(primary_key=True, serialize=False)),
                ('cultura', models.TextField(max_length=40)),
                ('data_plantio', models.DateField()),
                ('data_colheita', models.DateField()),
                ('quantidade_colhida', models.FloatField()),
            ],
        ),
    ]
